// <auto-generated />
using System;
using DAL.DBContexs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(GymDBContext))]
    partial class GymDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DAL.Model.Datlich", b =>
                {
                    b.Property<string>("IdPhieudatlich")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdKhachhang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhachHangIdKhachhang")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Ngaydatlich")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPhieudatlich");

                    b.HasIndex("KhachHangIdKhachhang");

                    b.ToTable("DatLich");
                });

            modelBuilder.Entity("DAL.Model.Datlichchitiet", b =>
                {
                    b.Property<string>("IdCT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DatLichIdPhieudatlich")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ghichu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Gioibatdau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Gioketthuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdPT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdPhieudatlich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngaydatlich")
                        .HasColumnType("datetime2");

                    b.Property<string>("PTMaPT")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCT");

                    b.HasIndex("DatLichIdPhieudatlich");

                    b.HasIndex("PTMaPT");

                    b.ToTable("DatLichChitiet");
                });

            modelBuilder.Entity("DAL.Model.Dichvu", b =>
                {
                    b.Property<string>("IdDichvu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ghichu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gia")
                        .HasColumnType("int");

                    b.Property<string>("Tendichvu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Thoihan")
                        .HasColumnType("datetime2");

                    b.HasKey("IdDichvu");

                    b.ToTable("DichVu");
                });

            modelBuilder.Entity("DAL.Model.Giamgia", b =>
                {
                    b.Property<string>("IdGG")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("GiaGiam")
                        .HasColumnType("real");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngayhethan")
                        .HasColumnType("datetime2");

                    b.HasKey("IdGG");

                    b.ToTable("giamgia");
                });

            modelBuilder.Entity("DAL.Model.Hoadon", b =>
                {
                    b.Property<string>("IdNhanvien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Giamgia")
                        .HasColumnType("real");

                    b.Property<string>("IdHoadon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdKhachhang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhachHangIdKhachhang")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Ngaylap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienMaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Thanhtien")
                        .HasColumnType("int");

                    b.Property<int>("Tongtien")
                        .HasColumnType("int");

                    b.Property<int>("Tongtienthanhtoan")
                        .HasColumnType("int");

                    b.Property<string>("Trangthaihoadon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthaithanhtoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNhanvien");

                    b.HasIndex("KhachHangIdKhachhang");

                    b.HasIndex("NhanVienMaNhanVien");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("DAL.Model.Hoadonchitiet", b =>
                {
                    b.Property<string>("IdHoadonchitiet")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DichVuIdDichvu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<string>("GiamGiaIdGG")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Giamgia")
                        .HasColumnType("real");

                    b.Property<string>("HoaDonIdNhanvien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdDichVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdGG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdHoadon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdKhachhang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhachHangIdKhachhang")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Tiencanthanhtoan")
                        .HasColumnType("float");

                    b.Property<double>("Tiencoctruoc")
                        .HasColumnType("float");

                    b.HasKey("IdHoadonchitiet");

                    b.HasIndex("DichVuIdDichvu");

                    b.HasIndex("GiamGiaIdGG");

                    b.HasIndex("HoaDonIdNhanvien");

                    b.HasIndex("KhachHangIdKhachhang");

                    b.ToTable("HoaDonChiTiet");
                });

            modelBuilder.Entity("DAL.Model.Hopdong", b =>
                {
                    b.Property<string>("IdHopdong")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HopDongIdHopdong")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdDichvu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdKhachhang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaPT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngaydangki")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngaykethuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PTMaPT")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdHopdong");

                    b.HasIndex("HopDongIdHopdong");

                    b.HasIndex("PTMaPT");

                    b.ToTable("hopdong");
                });

            modelBuilder.Entity("DAL.Model.KhachHang", b =>
                {
                    b.Property<string>("IdKhachhang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gioitinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<int>("SDT")
                        .HasColumnType("int");

                    b.Property<string>("Tenkhachhang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKhachhang");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("DAL.Model.LichLamviec", b =>
                {
                    b.Property<string>("IdLich")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdPT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<string>("PTMaPT")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdLich");

                    b.HasIndex("PTMaPT");

                    b.ToTable("LichLamViec");
                });

            modelBuilder.Entity("DAL.Model.Lichsuthanhtoan", b =>
                {
                    b.Property<string>("IdThanhtoan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HoaDonIdNhanvien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdHoadon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdPhuonthuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngaythanhtoan")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucThanhToanIdPhongthuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdThanhtoan");

                    b.HasIndex("HoaDonIdNhanvien");

                    b.HasIndex("PhuongThucThanhToanIdPhongthuc");

                    b.ToTable("LichSuThanhToan");
                });

            modelBuilder.Entity("DAL.Model.LoaiThietBi", b =>
                {
                    b.Property<string>("MaLoaiThetBi")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChucNang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("KhoiLuong")
                        .HasColumnType("float");

                    b.Property<string>("MauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenLoaiThietBi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoaiThetBi");

                    b.ToTable("LoaiThietBi");
                });

            modelBuilder.Entity("DAL.Model.Nhanvien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Chucvu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ghichi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gioitinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<int>("SDT")
                        .HasColumnType("int");

                    b.Property<string>("TenNhanvien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhanVien");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("DAL.Model.PhieuThongKe", b =>
                {
                    b.Property<string>("MaPhieu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhieu");

                    b.ToTable("PhieuThongKe");
                });

            modelBuilder.Entity("DAL.Model.Phuongthucthanhtoan", b =>
                {
                    b.Property<string>("IdPhongthuc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPhongthuc");

                    b.ToTable("phuongthucthanhtoan");
                });

            modelBuilder.Entity("DAL.Model.PT", b =>
                {
                    b.Property<string>("MaPT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChucNang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPT");

                    b.ToTable("PT");
                });

            modelBuilder.Entity("DAL.Model.ThietBi", b =>
                {
                    b.Property<string>("MaThietBi")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaLoaiThietBi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenThietBi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaThietBi");

                    b.HasIndex("MaLoaiThietBi");

                    b.ToTable("ThietBi");
                });

            modelBuilder.Entity("DAL.Model.ThongKeChiTiet", b =>
                {
                    b.Property<string>("MaPhieuCT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLoaiThietBi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaPhieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaThietBi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhaCungCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhieuThongKeMaPhieu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("SoLuong")
                        .HasColumnType("float");

                    b.Property<string>("TenLoaiThietBi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThietBi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThietBiMaThietBi")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhieuCT");

                    b.HasIndex("PhieuThongKeMaPhieu");

                    b.HasIndex("ThietBiMaThietBi");

                    b.ToTable("ThongKeChiTiet");
                });

            modelBuilder.Entity("DAL.Model.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DAL.Model.Datlich", b =>
                {
                    b.HasOne("DAL.Model.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangIdKhachhang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("DAL.Model.Datlichchitiet", b =>
                {
                    b.HasOne("DAL.Model.Datlich", "DatLich")
                        .WithMany()
                        .HasForeignKey("DatLichIdPhieudatlich");

                    b.HasOne("DAL.Model.PT", "PT")
                        .WithMany()
                        .HasForeignKey("PTMaPT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatLich");

                    b.Navigation("PT");
                });

            modelBuilder.Entity("DAL.Model.Hoadon", b =>
                {
                    b.HasOne("DAL.Model.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangIdKhachhang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Model.Nhanvien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienMaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DAL.Model.Hoadonchitiet", b =>
                {
                    b.HasOne("DAL.Model.Dichvu", "DichVu")
                        .WithMany()
                        .HasForeignKey("DichVuIdDichvu");

                    b.HasOne("DAL.Model.Giamgia", "GiamGia")
                        .WithMany()
                        .HasForeignKey("GiamGiaIdGG");

                    b.HasOne("DAL.Model.Hoadon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("HoaDonIdNhanvien");

                    b.HasOne("DAL.Model.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangIdKhachhang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("GiamGia");

                    b.Navigation("HoaDon");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("DAL.Model.Hopdong", b =>
                {
                    b.HasOne("DAL.Model.Hopdong", "HopDong")
                        .WithMany()
                        .HasForeignKey("HopDongIdHopdong");

                    b.HasOne("DAL.Model.PT", "PT")
                        .WithMany()
                        .HasForeignKey("PTMaPT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");

                    b.Navigation("PT");
                });

            modelBuilder.Entity("DAL.Model.LichLamviec", b =>
                {
                    b.HasOne("DAL.Model.PT", "PT")
                        .WithMany()
                        .HasForeignKey("PTMaPT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PT");
                });

            modelBuilder.Entity("DAL.Model.Lichsuthanhtoan", b =>
                {
                    b.HasOne("DAL.Model.Hoadon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("HoaDonIdNhanvien");

                    b.HasOne("DAL.Model.Phuongthucthanhtoan", "PhuongThucThanhToan")
                        .WithMany()
                        .HasForeignKey("PhuongThucThanhToanIdPhongthuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("PhuongThucThanhToan");
                });

            modelBuilder.Entity("DAL.Model.ThietBi", b =>
                {
                    b.HasOne("DAL.Model.LoaiThietBi", "LoaiThietBi")
                        .WithMany()
                        .HasForeignKey("MaLoaiThietBi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiThietBi");
                });

            modelBuilder.Entity("DAL.Model.ThongKeChiTiet", b =>
                {
                    b.HasOne("DAL.Model.PhieuThongKe", "PhieuThongKe")
                        .WithMany()
                        .HasForeignKey("PhieuThongKeMaPhieu");

                    b.HasOne("DAL.Model.ThietBi", "ThietBi")
                        .WithMany()
                        .HasForeignKey("ThietBiMaThietBi");

                    b.Navigation("PhieuThongKe");

                    b.Navigation("ThietBi");
                });
#pragma warning restore 612, 618
        }
    }
}
